"""Add firebase_uid to Patient model

Revision ID: 8a6e0d85070e
Revises: 70ad3027d91f
Create Date: 2025-06-29 03:21:38.318606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6e0d85070e'
down_revision = '70ad3027d91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_firebase_uid'), ['firebase_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_firebase_uid'))
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
