"""Add patient app models - routes and apis

Revision ID: bedbc1c423c8
Revises: 7bc7db3a02d6
Create Date: 2025-06-18 14:32:08.661396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedbc1c423c8'
down_revision = '7bc7db3a02d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entry_patient_id'), ['patient_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('sender_is_patient', sa.Boolean(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('read_by_recipient', sa.Boolean(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_patient_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_evaluation_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('weight_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entry_patient_id'))

    op.drop_table('weight_entry')
    # ### end Alembic commands ###
