"""add synonyms_json to ingredient table

Revision ID: d93980ba3975
Revises: e9115afa3cb7
Create Date: 2025-05-31 15:10:12.449390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93980ba3975'
down_revision = 'e9115afa3cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synonyms_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('synonyms_json')

    # ### end Alembic commands ###
